import { createI18n } from 'vue-i18n'

// Cargar los mensajes traducidos
const messages = {
  en: {
    welcome: 'Welcome',
    capacity: 'Capacity',

    search_placeholder: 'Search by name',
    pickup: 'Pickup -',

    all: 'All',
    vehicle_type: 'Vehicle Type',
    luggage: 'Luggage',
    people: 'People',
    suitcase: 'Suitcase',
    people_2: '2 People',
    people_4: '4 People',
    people_5: '5 People',
    people_7: '7 People',
    people_9: '9 People',
    luggage_2: '2 Suitcases',
    luggage_4: '4 Suitcases',
    luggage_6: '6 Suitcases',
    transmission_any: 'Any transmission',
    transmission_manual: 'Manual',
    transmission_semi_automatic: 'Semi-Automatic',
    transmission_automatic: 'Automatic',
    features: 'Features',
    reset_filters: 'Reset Filters',
    no_vehicles_found: 'No vehicles found with the applied filters.',
    brand: 'Brand',
    price_per_day: 'Price per day',
    special_features: 'Special features',
    select: 'Select',
    heated_seats: 'Heated seats',
    protection_products: 'Protection Products',
    overview: 'Overview',
    order_details: 'Order Details',
    date_location: 'Date & Location',
    vehicle:'vehicle',
    about_us:'About Us',
    Rent:'Rent your vehicle',
    Find:'Find your ideal vehicle',
    selected_location:'Select a location',
    any_capacity: 'Any capacity',
    back: 'Back',
    continue: 'Continue',
    add_product: '+ Add',
    personal_effects_coverage: 'Personal effects coverage',
    per_day: '/per day',
    equipment: 'Equipment',
    secure_extra_equipment: 'Secure some extra equipment',
    quick_search: "Quick Search",
    add_extras: 'Add extras',
    safer_trip: 'Safer and more protected trip',
    damage_disclaimer: 'Damage disclaimer',
    more_info: 'More info',
    add_different_return_location:"Add a different return location",
    seats: "Seats",
    return_date: "Return Date",
    departure_date: "Departure date",
    pick_up_and_return:"PickUp & Return",
    About_vehicle:'Our vehicles',
    no_vehicle:'No vehicles available',   
    how_it_works:'How it works',
    select_vehicle:'Select your car',
    browser:'Browse our fleet and choose the one that best suits your needs.',
    book_you:'Fill out the booking form with your details and trip dates.',
    book_you_ride:'Book Your Ride',
    enjoy:'Enjoy your trip!',
    enjoy_text:'Drive safely and enjoy your trip! Return the car at your convenience.',
    footer_text:'.All rights reserved',
 
  },
  es: {
    welcome: 'Bienvenido',
    search_placeholder: 'Buscar por nombre',
    capacity: 'Capacidad',
    all: 'Todas',
    vehicle_type: 'Tipo de Vehículo',
    luggage: 'Equipaje',
    any_capacity: 'Cualquier capacidad',
    people_2: '2 Personas',
    people_4: '4 Personas',
    people_5: '5 Personas',
    people_7: '7 Personas',
    people_9: '9 Personas',
    luggage_2: '2 Maletas',
    luggage_4: '4 Maletas',
    luggage_6: '6 Maletas',
    transmission_any: 'Cualquier transmisión',
    transmission_manual: 'Manual',
    transmission_semi_automatic: 'Semi-Automática',
    transmission_automatic: 'Automática',
    features: 'Características',
    reset_filters: 'Restablecer Filtros',
    no_vehicles_found: 'No se encontraron vehículos con los filtros aplicados.',
    brand: 'Marca',
    price_per_day: 'Precio por día',
    special_features: 'Características especiales',
    select: 'Seleccionar',
    heated_seats: 'Asientos calefaccionados',
    add_extras: 'Agregar extras',
    protection_products: 'Productos de Protección',
    safer_trip: 'Viaje más seguro y protegido',
    damage_disclaimer:'Exención de responsabilidad por daños',
    more_info: 'Más info',
    overview:'visión general',
    vehicle:'vehículo',
    date_location: 'Fecha y ubicación',
    pickup: 'Recogida -',


    about_us:'Acerca de nosotros',
    quick_search: "Búsqueda Rápida",
    back: 'Atrás',
    continue: 'Continuar',
    add_product: '+ Agregar',
    personal_effects_coverage: 'Cobertura de efectos personales',
    per_day: '/por día',
    equipment: 'Equipamiento',
    secure_extra_equipment: 'Asegure algún equipamiento extra',
    overview: 'Resumen',
    order_details: 'Detalles del pedido',








    
    Rent:'Renta tu vehiculó',
    Find:'Busca tu vehiculo ideal',
    pick_up_and_return:"Recogida y devolución",
    selected_location:'ubicación',
    pick_up_and_retur: "Recogida y Devolución",
    add_different_return_location:"ubicación diferente",
    seats: "Asientos",
    departure_date: "Fecha de salida",
    return_date: "Fecha de Retorno",
    About_vehicle:'Nuestros vehiculos',
    no_vehicle:'No hay vehiculos disponibles',
    how_it_works:'Como funciona',
    select_vehicle:'Selecciona tu vehiculo',
    browser:'Navegue por nuestra flota y elija la que mejor se adapte a sus necesidades.',
    book_you_ride:'Reserva tu viaje',
    book_you:'Complete el formulario de reserva con sus datos y fechas de viaje.',
    enjoy:'¡Disfruta de tu viaje!',
    enjoy_text:'¡Conduce con seguridad y disfruta de tu viaje! Devuelve el coche a tu conveniencia.',

    footer_text:' .Todos los derechos reservados'
    
  }
}

const i18n = createI18n({
  locale: 'en', // idioma por defecto
  fallbackLocale: 'en', // idioma alternativo
  messages,
})

export default i18n
